### ISSUE TITLE
installation issue - mapproj

### ISSUE THREAD

**Issue by iembry-USGS** [leonawicz/mapmate#1]
Hi, thank you for creating this R package.

I have unsuccessfully tried to install the package as it attempts to install `mapproj` which is already installed as in the system R library.

Can you direct the package to check all libraries for the dependencies prior to attempting to install them?

Thank you.

Irucka Embry

**Comment by leonawicz** [comment]
Hello,
The package automatically does these checks. I'm currently unable to reproduce the problem. I removed package dependencies like `mapproj` and then attempted to install `mapmapte` and that worked fine as well. My session info:

```
R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapmate_0.0.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.2.1      magrittr_1.5    R6_2.2.0        tools_3.3.1     withr_1.0.2     curl_2.1        memoise_1.0.0  
 [8] knitr_1.14      git2r_0.15.0    digest_0.6.10   devtools_1.12.0
```

Without more information I can only recommend making sure R is up to date as well as other R packages.

My attempts to install without `mapproj` already installed leads to `mapproj` being installed as expected when installing `mapmate`. With `mapproj` already installed, installation of `mapmate` does not attempt to reinstall `mapproj`.

R CMD check returns zero errors, warnings or notes (`devtools::check()`). The build also passes remotely on Travis-CI.

Regards,
Matt

**Comment by leonawicz** [comment]
Unable to reproduce the issue.

**Comment by iembry-USGS** [comment]
@leonawicz  - Thank you for your response. I have `mapproj` installed in the user library and also in the system library. The version in the system library is current, but the version in the user library is old.

I had asked if it was possible to have all libraries parsed to determine if the dependencies were available or not prior to installing them. I suggested this since `mapproj` can't be installed on my system (GNU/Linux Debian derivative) without using the root password.

Thank you again.

**Comment by leonawicz** [comment]
@iembry-USGS I have had similar issues with various packages in a server environment that I don't have root access to. I tend to just request the admin to install those for me (which may not be a convenient solution for all users). But this scenario is usually the real problem. There are plenty of special packages that I have had difficultlies with in server environments that I don't control.

As far as doing a package check on installation, as far as I am familiar any package will do these checks as long as all the package dependencies/imports are in place in the package. And if the package builds successfully in each Windows and Linux environment I check, I don't know what else could be done. In fact, the package won't build if I don't specify `mapproj` and other imported packages in the ways that I do. The build will fail and R will complain if I do it differently. If you are familiar with R package source files, let me know if there is something wrong somewhere in the source files that I am neglecting. I have been following Hadley Wickham's package development guide: http://r-pkgs.had.co.nz/
